spring.datasource.url=jdbc:postgresql://localhost:5432/attendance_system
spring.datasource.username=postgres
spring.datasource.password=Wc690213@

spring.jpa.show-sql=false
logging.level.com.example.attendance=INFO

server.port=8080