spring.application.name=attendance-system
spring.datasource.url=jdbc:postgresql://localhost:5432/attendance_system
spring.datasource.username=postgres
spring.datasource.password="Wc690213@"
spring.datasource.driver-class-name=org.postgresql.Driver
